### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joebowbeer**
## What did you implement:

Updated instructions in README to install current version.

## How did you implement it:

Replaced `0.21.0` with `0.21.2`.

## How can we verify it:

Eyesight.

## Todos:

- [ ] ~~Write tests~~
- [ ] ~~Write documentation~~
- [ ] ~~Fix linting errors~~
- [ ] ~~Tag `ready for review` or `wip`~~

***Is this a breaking change?:*** NO

### CODE REVIEW

**Comment by joebowbeer** [comment]
The coveralls config is broken? Is COVERALLS_REPO_TOKEN defined?

By the way, this PR addresses the same issue as #100

**Comment by joebowbeer** [comment]
Fixes #104

**Comment by jonsharratt** [comment]
Just sorting coveralls now 👍  Thanks for taking a look at this.

**Comment by jonsharratt** [comment]
Hey @joebowbeer can you update master into this branch and all should now pass via CircleCI.  I can then merge accordingly.  Had to sort CircleCI token for coveralls plus fix the nsp error from using an old GitHub module (#105).

👍

**Pull request merged**
